### ISSUE TITLE
"Unfortunately, Maps Geofavorites keeps stopping" and "Maps Geofavorites keeps stopping"

### ISSUE THREAD

**Issue by daffydock** [penguin86/nextcloud-maps-client#15] opened 2022-04-08 23:19 UTC
Downloaded lastest 2 versions of the app. Gave it required permissions. App starts and crashes aboit a second later. 

I tried it on my personal ID, which already has favourites, and it fails. Tried it on a different phone with an ID that has no prexisting map favourites and it works.

**Comment by penguin86** [comment] 2022-04-09 15:44
Hello @daffydock , thank for your report! Can you confirm you are running version 0.3.5? Also, did you import your geofavorites from Google Maps?

Unfortunately, I need to reproduce the problem to fix it, so here are some possibilities:
- you may provide a bookmarks export (may be sufficient a single bookmark as long as makes the app crash)
- you may provide the crash stacktrace (you can collect it with apps like [this one if you have a rooted device](https://f-droid.org/en/packages/com.pluscubed.matloglibre/) or [this one on a stock device](https://f-droid.org/en/packages/com.tananaev.logcat/).
- you may provide access to a Nextcloud account that causes the problem (preferably without personal data)

If you choose to provide the logs with the second application ("Logs") do not follow the utterly complicated instrucitions in the app, but simply go to Settings -> System -> Developer options and enable "ADB through network".
Let me know if you need more support.

**Comment by daffydock** [comment] 2022-05-09 22:07
Hi. Indeed I was running 0.3.5
I imported. I installed. Ran, and it crashes/closes. Immediately. 

It may help to know that on that phone, I am using Android 7. On a phone running 10, it works. Albeit that is a different Nexcloud account with no bookmarks. 

I will take a look at the app you suggested.

**Comment by penguin86** [comment] 2022-05-11 06:36
Hello @daffydock,
I think it may depend on the dataset, not the Android version. There may be some inconsistencies in the JSON due to the import (this happened and has been fixed in the past for the Google Maps imports).

Unfortunately I need to be able to reproduce the problem to fix it. Another option for reporting is to download the app via the Google Play Store and submit a report when the app crashes. This cannot be done when the app is installed via F-Droid or downloading the APK, because uses Google's error reporting system.

**Comment by realpixelcode** [comment] 2022-07-21 10:27
I can confirm this for version 0.3.5 on Android 11 with existing favourites already stored in NextCloud.

**Comment by wftmate** [comment] 2023-02-06 06:51
I've had the same issue. I downloaded the app from F-Droid as I am using Graphene OS. I have favorites already stored in my nextcloud instance but, I did not import them from google maps; they were created in the Nextcloud Maps App in a web browser.

I'm not sure if the information below is the same as the crash stacktrace you mentioned.

App Version: 0.3.5
Android Version: 13 (GrapheneOS on Pixel 4a)

-------------------------------------------------------------------------
type: crash
osVersion: google/sunfish/sunfish:13/TQ1A.230105.001/2023020200:user/release-keys
package: it.danieleverducci.nextcloudmaps:7
process: it.danieleverducci.nextcloudmaps
processUptime: 592 + 60 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at java.io.StringReader.<init>(StringReader.java:50)
	at android.text.HtmlToSpannedConverter.convert(Html.java:751)
	at android.text.Html.fromHtml(Html.java:246)
	at android.text.Html.fromHtml(Html.java:189)
	at it.danieleverducci.nextcloudmaps.activity.main.GeofavoriteAdapter.onBindViewHolder(GeofavoriteAdapter.java:114)
	at it.danieleverducci.nextcloudmaps.activity.main.GeofavoriteAdapter.onBindViewHolder(GeofavoriteAdapter.java:52)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:98)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1581)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:691)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
	at android.view.View.measure(View.java:26364)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1656)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:601)
	at android.view.View.measure(View.java:26364)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
	at android.view.View.measure(View.java:26364)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
	at android.view.View.measure(View.java:26364)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:26364)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26364)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26364)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26364)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26364)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
	at android.view.View.measure(View.java:26364)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3922)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2608)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2880)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2324)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9076)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Comment by penguin86** [comment] 2023-02-15 07:31
Thank you @wftmate , that is exactly what I needed to identify the problem! Seems like the name is NULL for (at least one) of yours geofavorites. This should never happen, BTW i placed a check to display an empty string in such cases.
Can you please check this edit fixes the problem for you? You can find an apk built on the fly here: https://ichibi.eu/index.php/s/RjRB8GZZASpZFe7
@daffydock @realpixelcode Can you also check this APK and see if the problem is fixed for you as well?
Thank you all!

**Comment by realpixelcode** [comment] 2023-02-15 08:41
@penguin86 I can confirm that it works now, thank you! Indeed, except for 3 favourites, none have a name. (I remember that I found it too tedious entering a name for each new one so I just didn't.)

**Comment by daffydock** [comment] 2023-02-15 20:39
@penguin86 

Checked. Apps starts and seems to work!

**Closed** 2023-02-17 06:16 UTC

**Comment by penguin86** [comment] 2023-02-17 06:35
Thank you all! I've pushed the fix on github, hopefully F-Droid will pick it up in the next hours and build it. It should be available in a couple of days.
